### ISSUE TITLE
SSE transport event stream format

### ISSUE THREAD

**Issue by tmaxmax** [MegaGrindStone/go-mcp#1]
Hi there, I'm the person on Reddit that raised the issue pertaining to the SSE stream parsing. I'm opening this issue to indicate another possible issue with the way server-sent events are handled here.

The [MCP specification](https://spec.modelcontextprotocol.io/specification/basic/transports/#http-with-sse) indicates the following:

> When a client connects, the server MUST send an `endpoint` event containing a URI for the client to use for sending messages. All subsequent client messages MUST be sent as HTTP POST requests to this endpoint.
>
> Server messages are sent as SSE `message` events, with the message content encoded as JSON in the event data.

When considering this together with the [SSE specification (Interpreting an event stream)](https://html.spec.whatwg.org/multipage/server-sent-events.html#event-stream-interpretation), it would result that the MCP spec defines two possible event formats:
```
event: endpoint
data: <the endpoint>
```
and
```
event: message
data: <the JSON payload>
```
Right now it seems that in the code here the following is attempted to be parsed:
```
endpoint: <the endpoint>

message: <the JSON payload>
```
The concepts of an "event" and respectively of an "event data" are well defined by the SSE specification, which also defines their corresponding fields in the wire format. The wire format contains four valid fields, namely `id`, `event`, `data` and `retry`. `go-mcp` seems to use field types which are not defined by the specification. 

Let me know if my reading of the specification is actually wrong. Hope this helps!

**Comment by MegaGrindStone** [comment]
Hi there man!

I think you're right. I just confirm it on MCP official python implementation. Specifically, [this line](https://github.com/modelcontextprotocol/python-sdk/blob/59fff69c3876a0f47b1b25607261cab7dbede33c/src/mcp/server/sse.py#L109). How come I missed that!

Btw, thanks to you, I've spent the Christmas holiday implementing the `Transport` interfaces. A big refactor, but it's worth it. The code looks cleaner and less hackish. It's almost done. So, I might fix this after that.

Thanks a lot, man.

**Comment by MegaGrindStone** [comment]
@tmaxmax I'm done implementing `Transport` interface. Would you like and have some time to make a pull request for this? It's okay for me if you can't find a time, though.

**Comment by tmaxmax** [comment]
hi there! I've opened #3 to tackle this.
